import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/fonts";
import Sidebar from "./ui/sidebar";

export const metadata: Metadata = {
  title: "todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased dot-pattern flex flex-auto flex-col sm:flex-row`}
      >
        <Sidebar />

        <div className="w-full h-full md:h-screen flex flex-col md:flex-row px-4 sm:py-12 pb-4 sm:px-64 gap-16 justify-evenly">
          {children}
        </div>
      </body>
    </html>
  );
}
